=== AdamMil/WebDAV.Server/Server/Resources/MediaTypes.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
AdamMil.WebDAV.Server is a library providing a flexible, extensible, and fairly
standards-compliant WebDAV server for the .NET Framework.

http://www.adammil.net/
Written 2012-2013 by Adam Milazzo.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
-->
<xs:schema targetNamespace="http://adammil.net/webdav.server/mediaTypes" elementFormDefault="qualified"
           xmlns="http://adammil.net/webdav.server/mediaTypes"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="mediaType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z0-9!#\$%&amp;'\*\+\-\.\^_`\|~]+/[a-zA-Z0-9!#\$%&amp;'\*\+\-\.\^_`\|~]+" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="extension">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^\.].*" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:element name="mediaTypeMap">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="entry" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="mediaType" type="mediaType" use="required" />
            <xs:attribute name="extension" type="extension" use="required" />
            <xs:attribute name="canonicalExtension" type="xs:boolean" default="false" />
            <xs:attribute name="canonicalMediaType" type="xs:boolean" default="true" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="defaultExtension" type="extension" />
      <xs:attribute name="defaultMediaType" type="mediaType" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AdamMil/WebDAV.Server/Server/Resources/MediaTypes.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- This file contains the default media type map. Changes to this file only
     take effect when the server is compiled, but you can modify this file and
     link the modified version into a site using web.config. See
     web.config.sample for details. (Search for "mediaTypeMap".)
-->
<!--
AdamMil.WebDAV.Server is a library providing a flexible, extensible, and fairly
standards-compliant WebDAV server for the .NET Framework.

http://www.adammil.net/
Written 2012-2015 by Adam Milazzo.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
-->
<mediaTypeMap xmlns="http://adammil.net/webdav.server/mediaTypes"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://adammil.net/webdav.server/mediaTypes MediaTypes.xsd">
  <entry mediaType="application/A2L" extension="a2l" />
  <entry mediaType="application/AML" extension="aml" />
  <entry mediaType="application/ATF" extension="atf" />
  <entry mediaType="application/ATFX" extension="atfx" />
  <entry mediaType="application/atom+xml" extension="atom" />
  <entry mediaType="application/atomcat+xml" extension="atomcat" />
  <entry mediaType="application/atomdeleted+xml" extension="atomdeleted" />
  <entry mediaType="application/atomsvc+xml" extension="atomsvc" />
  <entry mediaType="application/ATXML" extension="atxml" />
  <entry mediaType="application/bacnet-xdd+zip" extension="xdd" />
  <entry mediaType="application/calendar+xml" extension="xcs" />
  <entry mediaType="application/cbor" extension="cbor" />
  <entry mediaType="application/ccmp+xml" extension="ccmp" />
  <entry mediaType="application/CDFX+XML" extension="cdfx" />
  <entry mediaType="application/cdmi-capability" extension="cdmia" />
  <entry mediaType="application/cdmi-container" extension="cdmic" />
  <entry mediaType="application/cdmi-domain" extension="cdmid" />
  <entry mediaType="application/cdmi-object" extension="cdmio" />
  <entry mediaType="application/cdmi-queue" extension="cdmiq" />
  <entry mediaType="application/CEA" extension="cea" />
  <entry mediaType="application/cea-2018+xml" extension="xml" canonicalMediaType="false" />
  <entry mediaType="application/cellml+xml" extension="cellml" />
  <entry mediaType="application/cms" extension="cmsc" />
  <entry mediaType="application/coap-group+json" extension="json" canonicalMediaType="false" />
  <entry mediaType="application/cpl+xml" extension="cpl" />
  <entry mediaType="application/csrattrs" extension="csrattrs" />
  <entry mediaType="application/dash+xml" extension="mpd" />
  <entry mediaType="application/dashdelta" extension="mpdd" />
  <entry mediaType="application/davmount+xml" extension="davmount" />
  <entry mediaType="application/DCD" extension="dcd" />
  <entry mediaType="application/dicom" extension="dcm" />
  <entry mediaType="application/DII" extension="dii" />
  <entry mediaType="application/directx" extension="x" />
  <entry mediaType="application/DIT" extension="dit" />
  <entry mediaType="application/dskpp+xml" extension="xmls" />
  <entry mediaType="application/dssc+der" extension="dssc" />
  <entry mediaType="application/dssc+xml" extension="xdssc" />
  <entry mediaType="application/dvcs" extension="dvc" />
  <entry mediaType="application/ecmascript" extension="es" canonicalMediaType="true" />
  <entry mediaType="application/emotionml+xml" extension="emotionml" />
  <entry mediaType="application/epp+xml" extension="xml" canonicalMediaType="false" />
  <entry mediaType="application/epub+zip" extension="epub" />
  <entry mediaType="application/exi" extension="exi" />
  <entry mediaType="application/envoy" extension="evy" />
  <entry mediaType="application/fastinfoset" extension="finf" />
  <entry mediaType="application/fdt+xml" extension="fdt" />
  <entry mediaType="application/fits" extension="fits" canonicalMediaType="true" />
  <entry mediaType="application/font-sfnt" extension="ttf" canonicalExtension="true" canonicalMediaType="true" />
  <entry mediaType="application/font-sfnt" extension="otf" canonicalMediaType="true" />
  <entry mediaType="application/font-tdpfr" extension="pfr" canonicalMediaType="true" />
  <entry mediaType="application/font-woff" extension="woff" canonicalMediaType="true" />
  <entry mediaType="application/fractals" extension="fif" />
  <entry mediaType="application/futuresplash" extension="spl" />
  <entry mediaType="application/gzip" extension="gz" canonicalMediaType="true" />
  <entry mediaType="application/held+xml" extension="heldxml" />
  <entry mediaType="application/hta" extension="hta" />
  <entry mediaType="application/inkml+xml" extension="ink" />
  <entry mediaType="application/inkml+xml" extension="inkml" />
  <entry mediaType="application/internet-property-stream" extension="acx" />
  <entry mediaType="application/ipfix" extension="ipfix" />
  <entry mediaType="application/its+xml" extension="its" />
  <entry mediaType="application/java-archive" extension="jar" canonicalMediaType="true" />
  <entry mediaType="application/javascript" extension="js" canonicalMediaType="true" />
  <entry mediaType="application/jrd+json" extension="jrd" />
  <entry mediaType="application/json" extension="json" canonicalMediaType="true" />
  <entry mediaType="application/json-patch+json" extension="json-patch" />
  <entry mediaType="application/ld+json" extension="jsonld" />
  <entry mediaType="application/link-format" extension="wlnk" />
  <entry mediaType="application/liquidmotion" extension="jck" canonicalExtension="true" />
  <entry mediaType="application/liquidmotion" extension="jcz" />
  <entry mediaType="application/lostsync+xml" extension="lostsyncxml" />
  <entry mediaType="application/LXF" extension="lxf" />
  <entry mediaType="application/mac-binhex40" extension="hqx" />
  <entry mediaType="application/mads+xml" extension="mads" />
  <entry mediaType="application/marc" extension="mrc" />
  <entry mediaType="application/marcxml+xml" extension="mrcx" />
  <entry mediaType="application/mathematica" extension="ma" />
  <entry mediaType="application/mathematica" extension="mb" canonicalExtension="true" />
  <entry mediaType="application/mathematica" extension="nb" canonicalMediaType="true" />
  <entry mediaType="application/mathml+xml" extension="mml" />
  <entry mediaType="application/metalink4+xml" extension="meta4" />
  <entry mediaType="application/mbox" extension="mbox" />
  <entry mediaType="application/mets+xml" extension="mets" />
  <entry mediaType="application/MF4" extension="mf4" />
  <entry mediaType="application/mods+xml" extension="mods" />
  <entry mediaType="application/mp21" extension="m21" />
  <entry mediaType="application/mp21" extension="mp21" canonicalExtension="true" />
  <entry mediaType="application/mp4" extension="mp4" canonicalExtension="true" canonicalMediaType="false" />
  <entry mediaType="application/mp4" extension="mpg4" canonicalMediaType="false" />
  <entry mediaType="application/mpeg4-iod" extension="mp4" canonicalExtension="true" canonicalMediaType="false" />
  <entry mediaType="application/mpeg4-iod" extension="mpg4" canonicalMediaType="false" />
  <entry mediaType="application/mpeg4-iod-xmt" extension="mp4" canonicalExtension="true" canonicalMediaType="false" />
  <entry mediaType="application/mpeg4-iod-xmt" extension="mpg4" canonicalMediaType="false" />
  <entry mediaType="application/msaccess" extension="accdb" canonicalExtension="true" />
  <entry mediaType="application/msaccess" extension="accde" />
  <entry mediaType="application/msaccess" extension="accdt" />
  <entry mediaType="application/msword" extension="doc" canonicalExtension="true" />
  <entry mediaType="application/msword" extension="dot" />
  <entry mediaType="application/mxf" extension="mxf" />
  <entry mediaType="application/ocsp-request" extension="orq" />
  <entry mediaType="application/ocsp-response" extension="ors" />
  <entry mediaType="application/octet-stream" extension="bin" canonicalExtension="true" />
  <entry mediaType="application/oda" extension="oda" />
  <entry mediaType="application/ODX" extension="odx" />
  <entry mediaType="application/oebps-package+xml" extension="opf" />
  <entry mediaType="application/ogg" extension="ogx" />
  <entry mediaType="application/oleobject" extension="ods" canonicalMediaType="false" />
  <entry mediaType="application/olescript" extension="axs" />
  <entry mediaType="application/onenote" extension="one" canonicalExtension="true" />
  <entry mediaType="application/onenote" extension="onea" />
  <entry mediaType="application/onenote" extension="onepkg" />
  <entry mediaType="application/onenote" extension="onetmp" />
  <entry mediaType="application/onenote" extension="onetoc" />
  <entry mediaType="application/onenote" extension="onetoc2" />
  <entry mediaType="application/opensearchdescription+xml" extension="osdx" />
  <entry mediaType="application/oxps" extension="oxps" />
  <entry mediaType="application/p2p-overlay+xml" extension="relo" />
  <entry mediaType="application/pdf" extension="pdf" />
  <entry mediaType="application/PDX" extension="pdx" />
  <entry mediaType="application/pgp-signature" extension="asc" />
