=== AdamMil/WebDAV.Server/Server/Resources/MimeMap.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="MimeMap" targetNamespace="http://adammil.net/webdav.server/mimeMap" elementFormDefault="qualified"
           xmlns="http://adammil.net/webdav.server/mimeMap"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="mimeType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-z0-9!#\$%&amp;'\*\+\-\.\^_`\|~]+/[a-z0-9!#\$%&amp;'\*\+\-\.\^_`\|~]+" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="extension">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^\.].*" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:element name="mimeMap">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="entry" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="mimeType" type="mimeType" use="required" />
            <xs:attribute name="extension" type="extension" use="required" />
            <xs:attribute name="canonicalExtension" type="xs:boolean" default="false" />
            <xs:attribute name="canonicalMimeType" type="xs:boolean" default="true" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="defaultExtension" type="extension" />
      <xs:attribute name="defaultMimeType" type="mimeType" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AdamMil/WebDAV.Server/Server/Resources/MimeMap.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- the default MIME type map -->
<mimeMap xmlns="http://adammil.net/webdav.server/mimeMap"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://adammil.net/webdav.server/mimeMap MimeMap.xsd">
  <entry mimeType="application/atom+xml" extension="atom" />
  <entry mimeType="application/directx" extension="x" />
  <entry mimeType="application/ecmascript" extension="es" />
  <entry mimeType="application/exi" extension="exi" />
  <entry mimeType="application/envoy" extension="evy" />
  <entry mimeType="application/fractals" extension="fif" />
  <entry mimeType="application/futuresplash" extension="spl" />
  <entry mimeType="application/hta" extension="hta" />
  <entry mimeType="application/internet-property-stream" extension="acx" />
  <entry mimeType="application/java-archive" extension="jar" />
  <entry mimeType="application/javascript" extension="js" />
  <entry mimeType="application/json" extension="json" />
  <entry mimeType="application/liquidmotion" extension="jck" />
  <entry mimeType="application/liquidmotion" extension="jcz" />
  <entry mimeType="application/mac-binhex40" extension="hqx" />
  <entry mimeType="application/mathematica" extension="ma" />
  <entry mimeType="application/mathematica" extension="mb" canonicalExtension="true" />
  <entry mimeType="application/mathematica" extension="nb" />
  <entry mimeType="application/mathml+xml" extension="mml" />
  <entry mimeType="application/msaccess" extension="accdb" canonicalExtension="true" />
  <entry mimeType="application/msaccess" extension="accde" />
  <entry mimeType="application/msaccess" extension="accdt" />
  <entry mimeType="application/msword" extension="doc" canonicalExtension="true" />
  <entry mimeType="application/msword" extension="dot" />
  <entry mimeType="application/octet-stream" extension="bin" canonicalExtension="true" />
  <entry mimeType="application/oda" extension="oda" />
  <entry mimeType="application/olescript" extension="axs" />
  <entry mimeType="application/onenote" extension="one" canonicalExtension="true" />
  <entry mimeType="application/onenote" extension="onea" />
  <entry mimeType="application/onenote" extension="onepkg" />
  <entry mimeType="application/onenote" extension="onetmp" />
  <entry mimeType="application/onenote" extension="onetoc" />
  <entry mimeType="application/onenote" extension="onetoc2" />
  <entry mimeType="application/opensearchdescription+xml" extension="osdx" />
  <entry mimeType="application/pdf" extension="pdf" />
  <entry mimeType="application/pics-rules" extension="prf" />
  <entry mimeType="application/pkcs10" extension="p10" />
  <entry mimeType="application/pkcs7-mime" extension="p7c" />
  <entry mimeType="application/pkcs7-mime" extension="p7m" canonicalExtension="true" />
  <entry mimeType="application/pkcs7-signature" extension="p7s" />
  <entry mimeType="application/pkix-crl" extension="crl" />
  <entry mimeType="application/postscript" extension="ai" />
  <entry mimeType="application/postscript" extension="eps" />
  <entry mimeType="application/postscript" extension="ps" canonicalExtension="true" />
  <entry mimeType="application/rtf" extension="rtf" />
  <entry mimeType="application/set-payment-initiation" extension="setpay" />
  <entry mimeType="application/set-registration-initiation" extension="setreg" />
  <entry mimeType="application/sgml" extension="sgml" />
  <entry mimeType="application/streamingmedia" extension="ssm" />
  <entry mimeType="application/vcard+xml" extension="xml" canonicalExtension="true" canonicalMimeType="false" />
  <entry mimeType="application/vnd.fdf" extension="fdf" />
  <entry mimeType="application/vnd.ms-cab-compressed" extension="cab" />
  <entry mimeType="application/vnd.ms-excel" extension="xla" />
  <entry mimeType="application/vnd.ms-excel" extension="xlc" />
  <entry mimeType="application/vnd.ms-excel" extension="xlm" />
  <entry mimeType="application/vnd.ms-excel" extension="xls" canonicalExtension="true" />
  <entry mimeType="application/vnd.ms-excel" extension="xlt" />
  <entry mimeType="application/vnd.ms-excel" extension="xlw" />
  <entry mimeType="application/vnd.ms-excel.12" extension="xlsx" canonicalMimeType="false" />
  <entry mimeType="application/vnd.ms-excel.addin.12" extension="xlam" />
  <entry mimeType="application/vnd.ms-excel.binary.12" extension="xlsb" />
  <entry mimeType="application/vnd.ms-excel.macroenabled.12" extension="xlsm" />
  <entry mimeType="application/vnd.ms-excel.macroenabledtemplate.12" extension="xltm" />
  <entry mimeType="application/vnd.ms-excel.template.12" extension="xltx" canonicalMimeType="false" />
  <entry mimeType="application/vnd.ms-office.calx" extension="calx" />
  <entry mimeType="application/vnd.ms-officetheme" extension="thmx" />
  <entry mimeType="application/vnd.ms-pki.certstore" extension="sst" />
  <entry mimeType="application/vnd.ms-pki.pko" extension="pko" />
  <entry mimeType="application/vnd.ms-pki.seccat" extension="cat" />
  <entry mimeType="application/vnd.ms-pki.stl" extension="stl" />
  <entry mimeType="application/vnd.ms-powerpoint" extension="pot" />
  <entry mimeType="application/vnd.ms-powerpoint" extension="pps" />
  <entry mimeType="application/vnd.ms-powerpoint" extension="ppt" canonicalExtension="true" />
  <entry mimeType="application/vnd.ms-powerpoint.addin.12" extension="ppam" />
  <entry mimeType="application/vnd.ms-powerpoint.macroenabled.12" extension="pptm" />
  <entry mimeType="application/vnd.ms-powerpoint.presentation.12" extension="pptx" canonicalMimeType="false" />
  <entry mimeType="application/vnd.ms-powerpoint.show.12" extension="ppsx" canonicalMimeType="false" />
  <entry mimeType="application/vnd.ms-powerpoint.show.macroenabled.12" extension="ppsm" />
  <entry mimeType="application/vnd.ms-powerpoint.slide.macroenabled.12" extension="sldm" />
  <entry mimeType="application/vnd.ms-powerpoint.template.12" extension="potx" canonicalMimeType="false" />
  <entry mimeType="application/vnd.ms-powerpoint.template.macroenabled.12" extension="potm" />
  <entry mimeType="application/vnd.ms-project" extension="mpp" />
  <entry mimeType="application/vnd.ms-visio.viewer" extension="vdx" />
  <entry mimeType="application/vnd.ms-word.document.12" extension="docx" canonicalMimeType="false" />
  <entry mimeType="application/vnd.ms-word.document.macroenabled.12" extension="docm" />
  <entry mimeType="application/vnd.ms-word.template.12" extension="dotx" canonicalMimeType="false" />
  <entry mimeType="application/vnd.ms-word.template.macroenabled.12" extension="dotm" />
  <entry mimeType="application/vnd.ms-works" extension="wcm" />
  <entry mimeType="application/vnd.ms-works" extension="wdb" />
  <entry mimeType="application/vnd.ms-works" extension="wks" canonicalExtension="true" />
  <entry mimeType="application/vnd.ms-works" extension="wps" />
  <entry mimeType="application/vnd.ms-xpsdocument" extension="xps" />
  <entry mimeType="application/vnd.oasis.opendocument.presentation" extension="odp" />
  <entry mimeType="application/vnd.oasis.opendocument.spreadsheet" extension="ods" />
  <entry mimeType="application/vnd.oasis.opendocument.text" extension="odt" />
  <entry mimeType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" extension="xlsx" canonicalExtension="true" />
  <entry mimeType="application/vnd.openxmlformats-officedocument.spreadsheetml.template" extension="xltx" canonicalExtension="true" />
  <entry mimeType="application/vnd.openxmlformats-officedocument.presentationml.presentation" extension="pptx" canonicalExtension="true" />
  <entry mimeType="application/vnd.openxmlformats-officedocument.presentationml.slide" extension="sldx" />
  <entry mimeType="application/vnd.openxmlformats-officedocument.presentationml.slideshow" extension="ppsx" canonicalExtension="true" />
  <entry mimeType="application/vnd.openxmlformats-officedocument.presentationml.template" extension="potx" canonicalExtension="true" />
  <entry mimeType="application/vnd.openxmlformats-officedocument.wordprocessingml.document" extension="docx" canonicalExtension="true" />
  <entry mimeType="application/vnd.openxmlformats-officedocument.wordprocessingml.template" extension="dotx" canonicalExtension="true" />
  <entry mimeType="application/vnd.rn-realmedia" extension="rm" />
  <entry mimeType="application/vnd.visio" extension="vsd" canonicalExtension="true" />
  <entry mimeType="application/vnd.visio" extension="vss" />
  <entry mimeType="application/vnd.visio" extension="vst" />
  <entry mimeType="application/vnd.visio" extension="vsw" />
  <entry mimeType="application/vnd.visio" extension="vsx" />
  <entry mimeType="application/vnd.visio" extension="vtx" />
  <entry mimeType="application/vnd.wap.wmlc" extension="wmlc" />
  <entry mimeType="application/vnd.wap.wmlscriptc" extension="wmlsc" />
  <entry mimeType="application/winhlp" extension="hlp" />
  <entry mimeType="application/x-bcpio" extension="bcpio" />
  <entry mimeType="application/x-bittorrent" extension="torrent" />
  <entry mimeType="application/x-cdf" extension="cdf" />
  <entry mimeType="application/x-chm" extension="chm" />
  <entry mimeType="application/x-compress" extension="z" />
  <entry mimeType="application/x-compressed" extension="tgz" />
  <entry mimeType="application/x-cpio" extension="cpio" />
  <entry mimeType="application/x-csh" extension="csh" />
  <entry mimeType="application/x-director" extension="dcr" />
  <entry mimeType="application/x-director" extension="dir" canonicalExtension="true" />
  <entry mimeType="application/x-director" extension="dxr" />
  <entry mimeType="application/x-dvi" extension="dvi" />
  <entry mimeType="application/x-font-ttf" extension="ttf" />
  <entry mimeType="application/x-gtar" extension="gtar" />
  <entry mimeType="application/x-gzip" extension="gz" />
